
// Import the functions you need from the SDKs you need
import { initializeApp, getApps, getApp } from "firebase/app";
import { getAuth, setPersistence, browserLocalPersistence, Auth } from "firebase/auth";

// Your web app's Firebase configuration
// IMPORTANT: This object is generated by Firebase and should not be modified.
const firebaseConfig = {
  "projectId": "profitpilot-mxiko",
  "appId": "1:126683006269:web:b9464f902b322593687154",
  "storageBucket": "profitpilot-mxiko.firebasestorage.app",
  "apiKey": "AIzaSyA0y8IfhOiNmPTPQrljYrPaQXk3Ru5jaG4",
  "authDomain": "profitpilot-mxiko.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "126683006269"
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApp();
}

const auth = getAuth(app);

// Asynchronously set persistence and export the auth object
const authPromise = setPersistence(auth, browserLocalPersistence).then(() => auth).catch((error) => {
    console.error("Firebase persistence error:", error);
    // Fallback to returning the auth object anyway
    return auth;
});


export { app, authPromise };
