
// Import the functions you need from the SDKs you need
import { initializeApp, getApps } from "firebase/app";
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration
// IMPORTANT: This object is generated by Firebase and should not be modified.
const firebaseConfig = {
  "projectId": "profitpilot-mxiko",
  "appId": "1:126683006269:web:b9464f902b322593687154",
  "storageBucket": "profitpilot-mxiko.firebasestorage.app",
  "apiKey": "AIzaSyA0y8IfhOiNmPTPQrljYrPaQXk3Ru5jaG4",
  "authDomain": "profitpilot-mxiko.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "126683006269"
};

// Initialize Firebase
let app;
if (!getApps().length) {
  app = initializeApp(firebaseConfig);
} else {
  app = getApps()[0];
}


const auth = getAuth(app);

export { app, auth };
